"""The command surface at 0.6.2, frozen, plus the rendered help it produced.

Two fixtures, two jobs. `surface-0.6.2.json` is the compatibility guarantee:
every flag this tool had before the envelope landed, with its help text, its
choices and whether it was required. It is captured once and never
regenerated — a flag that disappears or changes meaning fails here, and the
only permitted differences are the ones named in ALLOWED_CHANGES with a
reason. Later packs add flags, so the check is subset, never equality.

`rendered.txt` is the rendered `--help` of every one of those commands,
regenerated by `scripts/capture_help.py` and compared byte for byte, so the
git diff of a surface change is a reader's proof of what moved. The command
list and the renderer are imported from that script rather than repeated, so
a command added to one is added to both. Byte for byte holds on one argparse
only: 3.13 changed how usage wraps and how `--keyword, --contains KEYWORD` is
spelled, so the fixture is captured on 3.13+ and the comparison skips below
it. The surface record above still runs on every version.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import pytest

from capture_help import COMMANDS, parser_for, render

FIXTURES = Path(__file__).parent / "fixtures" / "help"
SURFACE = json.loads((FIXTURES / "surface-0.6.2.json").read_text(encoding="utf-8"))

# The only differences a later change is allowed to make to a 0.6.2 flag, each
# with the reason it is allowed. An entry here still requires the flag to exist
# and to have actually changed, so a stale entry fails too.
#
# `--json PATH` keeps writing exactly the payload file it always wrote. The
# path merely became optional, so that bare `--json` means what the global
# flag means: print the envelope. Nothing that had a path before behaves
# differently.
ALLOWED_CHANGES: dict[tuple[str, str], str] = {
    ("discover", "--json"): "the path became optional; with none, the envelope goes to stdout",
    ("bot", "--json"): "the path became optional; with none, the envelope goes to stdout",
    ("search", "--format"): "gained jsonl, markdown and html; json and csv are written exactly as before",
}

FIELDS = ("option_strings", "help", "required", "choices", "nargs")


def command_name(path: tuple[str, ...]) -> str:
    return "root" if not path else " ".join(path)


def options_of(parser) -> dict[str, dict]:
    return {
        action.option_strings[0]: {
            "option_strings": list(action.option_strings),
            "help": action.help,
            "required": bool(action.required),
            "choices": sorted(action.choices) if action.choices else None,
            "nargs": action.nargs,
        }
        for action in parser._actions
        if action.option_strings
    }


def subcommands_of(parser) -> list[str]:
    for action in parser._actions:
        if not action.option_strings and getattr(action, "choices", None):
            return sorted(action.choices)
    return []


@pytest.mark.parametrize("path", COMMANDS, ids=command_name)
def test_every_0_6_2_flag_survives(path):
    name = command_name(path)
    frozen = SURFACE.get(name)
    if frozen is None:
        pytest.skip(f"{name} is newer than 0.6.2; it has no compatibility record to keep")
    current = options_of(parser_for(path))

    for flag, before in frozen["options"].items():
        assert flag in current, f"{name} lost {flag}"
        if (name, flag) in ALLOWED_CHANGES:
            # A named change still has to be a change: the flag is there, it
            # means the same thing, and only its argument shape may differ.
            assert current[flag] != before, (
                f"{name} {flag} is listed in ALLOWED_CHANGES but did not change; drop the entry"
            )
            continue
        for field in FIELDS:
            assert current[flag][field] == before[field], f"{name} {flag} changed its {field}"


@pytest.mark.parametrize("path", COMMANDS, ids=command_name)
def test_every_0_6_2_subcommand_survives(path):
    name = command_name(path)
    if name not in SURFACE:
        pytest.skip(f"{name} is newer than 0.6.2; it has no compatibility record to keep")
    for subcommand in SURFACE[name]["subcommands"]:
        assert subcommand in subcommands_of(parser_for(path)), f"{name} lost the {subcommand} subcommand"


@pytest.mark.skipif(sys.version_info < (3, 13), reason="argparse renders differently before 3.13; the fixture is captured on 3.13+")
def test_rendered_help_matches_its_fixture():
    assert render() == (FIXTURES / "rendered.txt").read_text(encoding="utf-8"), (
        "--help changed; run scripts/capture_help.py and read the diff"
    )
